name = "medium-ankit"
main = "src/index.ts"
compatibility_date = "2024-11-13"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL=""
DIRECT_URL="<YOUR_DATABASE_CONNECTION_STRING>"

JWT_SECRET = ""

external_modules = ["medium-ankit"]

